### PR TITLE
Add open issues analysis

### PR DESCRIPTION
**Pull request by fcollonval**
Following the dev meeting of July 7th, here is a notebook that analyze the JupyterLab opened issues.

Xref: https://github.com/jupyterlab/team-compass/issues/117#issuecomment-875801069

The notebook can be visualized directly in GitHub: https://github.com/jupyterlab/team-compass/blob/ft/issues-insights/docs/insights/JupyterLab_issues.ipynb

### CODE REVIEW

**Comment by telamonian** [comment]
hmm, interesting. Apparently people were bringing up a lot of especially difficult issues at the start of 2018, for some reason

**Comment by krassowski** [comment]
Thanks @fcollonval. I will also take a stab at the text analysis during the weekend (if there won't be another heatwave...).

> hmm, interesting. Apparently people were bringing up a lot of especially difficult issues at the start of 2018, for some reason

Would be good to normalize by total number of issues opened at given time for that conclusion I think? There might have been a spike in total number of issues after https://blog.jupyter.org/jupyterlab-is-ready-for-users-5a6f039b8906 announcement.

**Comment by fcollonval** [comment]
> There might have been a spike in total number of issues after https://blog.jupyter.org/jupyterlab-is-ready-for-users-5a6f039b8906 announcement.

This sounds like a plausible cause as the peak is on the approximate second month. But you are correct, some normalization would make sense (and probably stricter construction of bin per month).

**Comment by telamonian** [comment]
> Would be good to normalize by total number of issues opened at given time for that conclusion I think? There might have been a spike in total number of issues after https://blog.jupyter.org/jupyterlab-is-ready-for-users-5a6f039b8906 announcement.

Yeah, sure, but doesn't a sudden plague of vexatious users sound much funnier?

+1 for adding some plots with bins normalized bins. That would help to sort out some of these possible hypothesis. Tho for the 2018 spike historical contingency does seem the likeliest explanation, given the preceding blogpost

**Comment by krassowski** [comment]
Is it possible to get reactions (:+1:, :-1:  etc) stats with this API? I am thinking like weighting n-grams by those...

**Comment by fcollonval** [comment]
> Is it possible to get reactions (+1, -1 etc) stats with this API? I am thinking like weighting n-grams by those...

This is possible although it will require more API request (see https://ghapi.fast.ai/fullapi.html#reactions and https://docs.github.com/en/rest/reference/reactions#list-reactions-for-an-issue). This means we may hit the GitHub anonymous request quota (I try to avoid bringing authentication for easiness).

**Pull request closed without merging**
