### PR TITLE
Update contributors.yaml

### PR DESCRIPTION
**Pull request by jtpio**
Reflecting the latest changes on the council repo.

Thanks @ivanov for your time and contributions, happy to have you back whenever you want!

### CODE REVIEW

**Comment by JasonWeill** [comment]
Can you also please remove me? I'm stepping down effective 2024-12-13. Thanks.

**Comment by jtpio** [comment]
> Can you also please remove me? I'm stepping down effective 2024-12-13. Thanks.

Sure. Would you be able to open a PR in https://github.com/jupyterlab/council too? Thanks!

**Comment by JasonWeill** [comment]
Done: https://github.com/jupyterlab/council/pull/26

**Review by JasonWeill — APPROVED** [review]

**Review by ivanov — APPROVED** [review]
thanks @jtpio

**Pull request merged**
